[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "50% 30%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"

[scratchpads.term_clock]
animation = "fromBottom"
command = "kitty --class kitty-dropterm tty-clock -c -s"
class = "kitty-dropterm"
size = "30% 30%"
unfocus = "hide"

[scratchpads.term_btop]
animation = "fromLeft"
command = "kitty --class kitty-dropterm btop"
class = "kitty-dropterm"
size = "30% 90%"
unfocus = "hide"

